[2025-05-10 01:04:24,105 ] 9 root - INFO - The execution has started...
[2025-05-10 01:04:26,214 ] 16 root - ERROR - An error occurred: Error occurred in script: [E:\ML projects\MLproject1\src\MLProject1\components\data_ingestion.py] at line number: [35] with error message: [cluster0-shard-00-01.o0y1c.mongodb.net:27017: timed out (configured timeouts: connectTimeoutMS: 20000.0ms)]
