[2025-05-12 00:01:07,025 ] 12 root - INFO - The execution has started...
[2025-05-12 00:01:07,025 ] 24 root - INFO - Fetching data from MongoDB...
[2025-05-12 00:01:07,025 ] 26 root - INFO - Connecting to MongoDB...
[2025-05-12 00:01:09,394 ] 40 root - INFO - Data successfully fetched from MongoDB.
[2025-05-12 00:01:09,398 ] 28 root - INFO - Loading local CSV data from notebook/data\student_raw.csv...
[2025-05-12 00:01:09,415 ] 30 root - INFO - Local CSV data successfully loaded.
[2025-05-12 00:01:09,415 ] 34 root - INFO - Merged MongoDB data with local CSV data.
[2025-05-12 00:01:09,433 ] 38 root - INFO - Raw data saved to artifacts\raw_data.csv
[2025-05-12 00:01:09,454 ] 44 root - INFO - Train/Test split saved at artifacts\train.csv and artifacts\test.csv
[2025-05-12 00:01:09,520 ] 72 root - INFO - Read train and test data completed
[2025-05-12 00:01:09,520 ] 53 root - INFO - Categorical Columns: ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
[2025-05-12 00:01:09,520 ] 54 root - INFO - Numerical Columns: ['writing_score', 'reading_score']
[2025-05-12 00:01:09,525 ] 88 root - INFO - Applying preprocessing on training and testing data
[2025-05-12 00:01:09,571 ] 96 root - INFO - Saved preprocessing object
[2025-05-12 00:01:09,574 ] 42 root - INFO - Split training and test input data
[2025-05-12 00:06:52,174 ] 29 root - ERROR - An error occurred: Error occurred in script: [E:\ML projects\MLproject1\src\MLProject1\components\model_trainer.py] at line number: [121] with error message: [API request to https://dagshub.com/SaiShashankBhiram/mlproject1.mlflow/api/2.0/mlflow/experiments/get failed with exception HTTPSConnectionPool(host='dagshub.com', port=443): Max retries exceeded with url: /SaiShashankBhiram/mlproject1.mlflow/api/2.0/mlflow/experiments/get?experiment_id=None (Caused by ResponseError('too many 500 error responses'))]
